name: Release
on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run build
      - run: git config --global user.name "github-actions[bot]"
      - run: git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: "npx standard-version --releaseCommitMessageFormat 'chore(release): [ci skip] {{currentTag}}'"
      - run: git push -u origin main
      - run: git push --tags
      - run: npm config set //npm.pkg.github.com/:_authToken=${NPM_TOKEN}
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm publish
